apiVersion: sources.knative.dev/v1beta1
kind: KafkaSource
metadata:
  name: kafka-source
  namespace: my-project
  labels:
    app: kafka-source
    app.kubernetes.io/instance: kafka-source
    app.kubernetes.io/component: kafka-source
    app.kubernetes.io/name: kafka-source
    app.kubernetes.io/part-of: event-sources-app
  annotations:
    openshift.io/generated-by: OpenShiftWebConsole
spec:
  bootstrapServers:
    - my-cluster-kafka-bootstrap.my-kafka.svc:9092
  topics:
    - my-topic
  consumerGroup: quarkus-sending-and-eventing
  sink:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: quarkus-serving-and-eventing-native
