kind: KnativeKafka
apiVersion: operator.serverless.openshift.io/v1alpha1
metadata:
  name: knative-kafka
  namespace: knative-eventing
spec:
  source:
    enabled: true
  channel:
        enabled: true 
        bootstrapServers: my-cluster-kafka-bootstrap.my-kafka.svc:9092
  broker:
        enabled: true 
        defaultConfig:
            bootstrapServers: my-cluster-kafka-bootstrap.my-kafka.svc:9092
            numPartitions: 3
            replicationFactor: 1