apiVersion: sources.knative.dev/v1
kind: PingSource
metadata:
  name: ping-source
  namespace: my-project
  labels:
    app: ping-source
    app.kubernetes.io/instance: ping-source
    app.kubernetes.io/component: ping-source
    app.kubernetes.io/name: ping-source
    app.kubernetes.io/part-of: event-sources-app
  annotations:
    openshift.io/generated-by: OpenShiftWebConsole
spec:
  spec:
  ceOverrides:
    extensions:
      extra: '0'
  contentType: application/json
  data: '{"message": "Hello world From Ping!"}' 
  schedule: '* * * * * '
  sink:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: quarkus-serving-and-eventing-native
